// pkzo
// Copyright 2010-2026 Sean Farrell
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files(the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions :
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#pragma once

#include <functional>
#include <variant>

#include <rsig/rsig.h>
#include <SDL3/SDL.h>
#include <glm/glm.hpp>
#include <magic_enum/magic_enum.hpp>

#include "api.h"

namespace pkzo
{
    using namespace magic_enum::bitwise_operators;

    enum class MouseButton : Uint8
    {
        LEFT    = SDL_BUTTON_LEFT,
        MIDDLE  = SDL_BUTTON_MIDDLE,
        RIGHT   = SDL_BUTTON_RIGHT,
        BUTTON4 = SDL_BUTTON_X1,
        BUTTON5 = SDL_BUTTON_X2
    };

    enum class KeyMod : Uint16
    {
        NONE   = SDL_KMOD_NONE,
        LSHIFT = SDL_KMOD_LSHIFT,
        RSHIFT = SDL_KMOD_RSHIFT,
        LEVEL5 = SDL_KMOD_LEVEL5,
        LCTRL  = SDL_KMOD_LCTRL,
        RCTRL  = SDL_KMOD_RCTRL,
        LALT   = SDL_KMOD_LALT,
        RALT   = SDL_KMOD_RALT,
        LGUI   = SDL_KMOD_LGUI,
        RGUI   = SDL_KMOD_RGUI,
        NUM    = SDL_KMOD_NUM,
        CAPS   = SDL_KMOD_CAPS,
        MODE   = SDL_KMOD_MODE,
        SCROLL = SDL_KMOD_SCROLL,
        CTRL   = SDL_KMOD_CTRL,
        SHIFT  = SDL_KMOD_SHIFT,
        ALT    = SDL_KMOD_ALT,
        GUI    = SDL_KMOD_GUI
    };

    enum class KeyCode : Uint32
    {
        UNKNOWN               =  SDLK_UNKNOWN,
        RETURN                =  SDLK_RETURN,
        ESCAPE                =  SDLK_ESCAPE,
        BACKSPACE             =  SDLK_BACKSPACE,
        TAB                   =  SDLK_TAB,
        SPACE                 =  SDLK_SPACE,
        EXCLAIM               =  SDLK_EXCLAIM,
        DBLAPOSTROPHE         =  SDLK_DBLAPOSTROPHE,
        HASH                  =  SDLK_HASH,
        DOLLAR                =  SDLK_DOLLAR,
        PERCENT               =  SDLK_PERCENT,
        AMPERSAND             =  SDLK_AMPERSAND,
        APOSTROPHE            =  SDLK_APOSTROPHE,
        LEFTPAREN             =  SDLK_LEFTPAREN,
        RIGHTPAREN            =  SDLK_RIGHTPAREN,
        ASTERISK              =  SDLK_ASTERISK,
        PLUS                  =  SDLK_PLUS,
        COMMA                 =  SDLK_COMMA,
        MINUS                 =  SDLK_MINUS,
        PERIOD                =  SDLK_PERIOD,
        SLASH                 =  SDLK_SLASH,
        ONE                   =  SDLK_0,
        TWO                   =  SDLK_1,
        THREE                 =  SDLK_2,
        FOUR                  =  SDLK_3,
        FIVE                  =  SDLK_4,
        SIX                   =  SDLK_5,
        SEVEN                 =  SDLK_6,
        EIGHT                 =  SDLK_7,
        NINE                  =  SDLK_8,
        ZERO                  =  SDLK_9,
        COLON                 =  SDLK_COLON,
        SEMICOLON             =  SDLK_SEMICOLON,
        LESS                  =  SDLK_LESS,
        EQUALS                =  SDLK_EQUALS,
        GREATER               =  SDLK_GREATER,
        QUESTION              =  SDLK_QUESTION,
        AT                    =  SDLK_AT,
        LEFTBRACKET           =  SDLK_LEFTBRACKET,
        BACKSLASH             =  SDLK_BACKSLASH,
        RIGHTBRACKET          =  SDLK_RIGHTBRACKET,
        CARET                 =  SDLK_CARET,
        UNDERSCORE            =  SDLK_UNDERSCORE,
        GRAVE                 =  SDLK_GRAVE,
        A                     =  SDLK_A,
        B                     =  SDLK_B,
        C                     =  SDLK_C,
        D                     =  SDLK_D,
        E                     =  SDLK_E,
        F                     =  SDLK_F,
        G                     =  SDLK_G,
        H                     =  SDLK_H,
        I                     =  SDLK_I,
        J                     =  SDLK_J,
        K                     =  SDLK_K,
        L                     =  SDLK_L,
        M                     =  SDLK_M,
        N                     =  SDLK_N,
        O                     =  SDLK_O,
        P                     =  SDLK_P,
        Q                     =  SDLK_Q,
        R                     =  SDLK_R,
        S                     =  SDLK_S,
        T                     =  SDLK_T,
        U                     =  SDLK_U,
        V                     =  SDLK_V,
        W                     =  SDLK_W,
        X                     =  SDLK_X,
        Y                     =  SDLK_Y,
        Z                     =  SDLK_Z,
        LEFTBRACE             =  SDLK_LEFTBRACE,
        PIPE                  =  SDLK_PIPE,
        RIGHTBRACE            =  SDLK_RIGHTBRACE,
        TILDE                 =  SDLK_TILDE,
        DELETE                =  SDLK_DELETE,
        PLUSMINUS             =  SDLK_PLUSMINUS,
        CAPSLOCK              =  SDLK_CAPSLOCK,
        F1                    =  SDLK_F1,
        F2                    =  SDLK_F2,
        F3                    =  SDLK_F3,
        F4                    =  SDLK_F4,
        F5                    =  SDLK_F5,
        F6                    =  SDLK_F6,
        F7                    =  SDLK_F7,
        F8                    =  SDLK_F8,
        F9                    =  SDLK_F9,
        F10                   =  SDLK_F10,
        F11                   =  SDLK_F11,
        F12                   =  SDLK_F12,
        PRINTSCREEN           =  SDLK_PRINTSCREEN,
        SCROLLLOCK            =  SDLK_SCROLLLOCK,
        PAUSE                 =  SDLK_PAUSE,
        INSERT                =  SDLK_INSERT,
        HOME                  =  SDLK_HOME,
        PAGEUP                =  SDLK_PAGEUP,
        END                   =  SDLK_END,
        PAGEDOWN              =  SDLK_PAGEDOWN,
        RIGHT                 =  SDLK_RIGHT,
        LEFT                  =  SDLK_LEFT,
        DOWN                  =  SDLK_DOWN,
        UP                    =  SDLK_UP,
        NUMLOCKCLEAR          =  SDLK_NUMLOCKCLEAR,
        KP_DIVIDE             =  SDLK_KP_DIVIDE,
        KP_MULTIPLY           =  SDLK_KP_MULTIPLY,
        KP_MINUS              =  SDLK_KP_MINUS,
        KP_PLUS               =  SDLK_KP_PLUS,
        KP_ENTER              =  SDLK_KP_ENTER,
        KP_1                  =  SDLK_KP_1,
        KP_2                  =  SDLK_KP_2,
        KP_3                  =  SDLK_KP_3,
        KP_4                  =  SDLK_KP_4,
        KP_5                  =  SDLK_KP_5,
        KP_6                  =  SDLK_KP_6,
        KP_7                  =  SDLK_KP_7,
        KP_8                  =  SDLK_KP_8,
        KP_9                  =  SDLK_KP_9,
        KP_0                  =  SDLK_KP_0,
        KP_PERIOD             =  SDLK_KP_PERIOD,
        APPLICATION           =  SDLK_APPLICATION,
        POWER                 =  SDLK_POWER,
        KP_EQUALS             =  SDLK_KP_EQUALS,
        F13                   =  SDLK_F13,
        F14                   =  SDLK_F14,
        F15                   =  SDLK_F15,
        F16                   =  SDLK_F16,
        F17                   =  SDLK_F17,
        F18                   =  SDLK_F18,
        F19                   =  SDLK_F19,
        F20                   =  SDLK_F20,
        F21                   =  SDLK_F21,
        F22                   =  SDLK_F22,
        F23                   =  SDLK_F23,
        F24                   =  SDLK_F24,
        EXECUTE               =  SDLK_EXECUTE,
        HELP                  =  SDLK_HELP,
        MENU                  =  SDLK_MENU,
        SELECT                =  SDLK_SELECT,
        STOP                  =  SDLK_STOP,
        AGAIN                 =  SDLK_AGAIN,
        UNDO                  =  SDLK_UNDO,
        CUT                   =  SDLK_CUT,
        COPY                  =  SDLK_COPY,
        PASTE                 =  SDLK_PASTE,
        FIND                  =  SDLK_FIND,
        MUTE                  =  SDLK_MUTE,
        VOLUMEUP              =  SDLK_VOLUMEUP,
        VOLUMEDOWN            =  SDLK_VOLUMEDOWN,
        KP_COMMA              =  SDLK_KP_COMMA,
        KP_EQUALSAS400        =  SDLK_KP_EQUALSAS400,
        ALTERASE              =  SDLK_ALTERASE,
        SYSREQ                =  SDLK_SYSREQ,
        CANCEL                =  SDLK_CANCEL,
        CLEAR                 =  SDLK_CLEAR,
        PRIOR                 =  SDLK_PRIOR,
        RETURN2               =  SDLK_RETURN2,
        SEPARATOR             =  SDLK_SEPARATOR,
        OUT                   =  SDLK_OUT,
        OPER                  =  SDLK_OPER,
        CLEARAGAIN            =  SDLK_CLEARAGAIN,
        CRSEL                 =  SDLK_CRSEL,
        EXSEL                 =  SDLK_EXSEL,
        KP_00                 =  SDLK_KP_00,
        KP_000                =  SDLK_KP_000,
        THOUSANDSSEPARATOR    =  SDLK_THOUSANDSSEPARATOR,
        DECIMALSEPARATOR      =  SDLK_DECIMALSEPARATOR,
        CURRENCYUNIT          =  SDLK_CURRENCYUNIT,
        CURRENCYSUBUNIT       =  SDLK_CURRENCYSUBUNIT,
        KP_LEFTPAREN          =  SDLK_KP_LEFTPAREN,
        KP_RIGHTPAREN         =  SDLK_KP_RIGHTPAREN,
        KP_LEFTBRACE          =  SDLK_KP_LEFTBRACE,
        KP_RIGHTBRACE         =  SDLK_KP_RIGHTBRACE,
        KP_TAB                =  SDLK_KP_TAB,
        KP_BACKSPACE          =  SDLK_KP_BACKSPACE,
        KP_A                  =  SDLK_KP_A,
        KP_B                  =  SDLK_KP_B,
        KP_C                  =  SDLK_KP_C,
        KP_D                  =  SDLK_KP_D,
        KP_E                  =  SDLK_KP_E,
        KP_F                  =  SDLK_KP_F,
        KP_XOR                =  SDLK_KP_XOR,
        KP_POWER              =  SDLK_KP_POWER,
        KP_PERCENT            =  SDLK_KP_PERCENT,
        KP_LESS               =  SDLK_KP_LESS,
        KP_GREATER            =  SDLK_KP_GREATER,
        KP_AMPERSAND          =  SDLK_KP_AMPERSAND,
        KP_DBLAMPERSAND       =  SDLK_KP_DBLAMPERSAND,
        KP_VERTICALBAR        =  SDLK_KP_VERTICALBAR,
        KP_DBLVERTICALBAR     =  SDLK_KP_DBLVERTICALBAR,
        KP_COLON              =  SDLK_KP_COLON,
        KP_HASH               =  SDLK_KP_HASH,
        KP_SPACE              =  SDLK_KP_SPACE,
        KP_AT                 =  SDLK_KP_AT,
        KP_EXCLAM             =  SDLK_KP_EXCLAM,
        KP_MEMSTORE           =  SDLK_KP_MEMSTORE,
        KP_MEMRECALL          =  SDLK_KP_MEMRECALL,
        KP_MEMCLEAR           =  SDLK_KP_MEMCLEAR,
        KP_MEMADD             =  SDLK_KP_MEMADD,
        KP_MEMSUBTRACT        =  SDLK_KP_MEMSUBTRACT,
        KP_MEMMULTIPLY        =  SDLK_KP_MEMMULTIPLY,
        KP_MEMDIVIDE          =  SDLK_KP_MEMDIVIDE,
        KP_PLUSMINUS          =  SDLK_KP_PLUSMINUS,
        KP_CLEAR              =  SDLK_KP_CLEAR,
        KP_CLEARENTRY         =  SDLK_KP_CLEARENTRY,
        KP_BINARY             =  SDLK_KP_BINARY,
        KP_OCTAL              =  SDLK_KP_OCTAL,
        KP_DECIMAL            =  SDLK_KP_DECIMAL,
        KP_HEXADECIMAL        =  SDLK_KP_HEXADECIMAL,
        LCTRL                 =  SDLK_LCTRL,
        LSHIFT                =  SDLK_LSHIFT,
        LALT                  =  SDLK_LALT,
        LGUI                  =  SDLK_LGUI,
        RCTRL                 =  SDLK_RCTRL,
        RSHIFT                =  SDLK_RSHIFT,
        RALT                  =  SDLK_RALT,
        RGUI                  =  SDLK_RGUI,
        MODE                  =  SDLK_MODE,
        SLEEP                 =  SDLK_SLEEP,
        WAKE                  =  SDLK_WAKE,
        CHANNEL_INCREMENT     =  SDLK_CHANNEL_INCREMENT,
        CHANNEL_DECREMENT     =  SDLK_CHANNEL_DECREMENT,
        MEDIA_PLAY            =  SDLK_MEDIA_PLAY,
        MEDIA_PAUSE           =  SDLK_MEDIA_PAUSE,
        MEDIA_RECORD          =  SDLK_MEDIA_RECORD,
        MEDIA_FAST_FORWARD    =  SDLK_MEDIA_FAST_FORWARD,
        MEDIA_REWIND          =  SDLK_MEDIA_REWIND,
        MEDIA_NEXT_TRACK      =  SDLK_MEDIA_NEXT_TRACK,
        MEDIA_PREVIOUS_TRACK  =  SDLK_MEDIA_PREVIOUS_TRACK,
        MEDIA_STOP            =  SDLK_MEDIA_STOP,
        MEDIA_EJECT           =  SDLK_MEDIA_EJECT,
        MEDIA_PLAY_PAUSE      =  SDLK_MEDIA_PLAY_PAUSE,
        MEDIA_SELECT          =  SDLK_MEDIA_SELECT,
        AC_NEW                =  SDLK_AC_NEW,
        AC_OPEN               =  SDLK_AC_OPEN,
        AC_CLOSE              =  SDLK_AC_CLOSE,
        AC_EXIT               =  SDLK_AC_EXIT,
        AC_SAVE               =  SDLK_AC_SAVE,
        AC_PRINT              =  SDLK_AC_PRINT,
        AC_PROPERTIES         =  SDLK_AC_PROPERTIES,
        AC_SEARCH             =  SDLK_AC_SEARCH,
        AC_HOME               =  SDLK_AC_HOME,
        AC_BACK               =  SDLK_AC_BACK,
        AC_FORWARD            =  SDLK_AC_FORWARD,
        AC_STOP               =  SDLK_AC_STOP,
        AC_REFRESH            =  SDLK_AC_REFRESH,
        AC_BOOKMARKS          =  SDLK_AC_BOOKMARKS,
        SOFTLEFT              =  SDLK_SOFTLEFT,
        SOFTRIGHT             =  SDLK_SOFTRIGHT,
        CALL                  =  SDLK_CALL,
        ENDCALL               =  SDLK_ENDCALL,
        LEFT_TAB              =  SDLK_LEFT_TAB,
        LEVEL5_SHIFT          =  SDLK_LEVEL5_SHIFT,
        MULTI_KEY_COMPOSE     =  SDLK_MULTI_KEY_COMPOSE,
        LMETA                 =  SDLK_LMETA,
        RMETA                 =  SDLK_RMETA,
        LHYPER                =  SDLK_LHYPER,
        RHYPER                =  SDLK_RHYPER
    };

    enum class ScanCode : std::underlying_type_t<SDL_Scancode>
    {
        UNKNOWN              = SDL_SCANCODE_UNKNOWN,
        A                    = SDL_SCANCODE_A,
        B                    = SDL_SCANCODE_B,
        C                    = SDL_SCANCODE_C,
        D                    = SDL_SCANCODE_D,
        E                    = SDL_SCANCODE_E,
        F                    = SDL_SCANCODE_F,
        G                    = SDL_SCANCODE_G,
        H                    = SDL_SCANCODE_H,
        I                    = SDL_SCANCODE_I,
        J                    = SDL_SCANCODE_J,
        K                    = SDL_SCANCODE_K,
        L                    = SDL_SCANCODE_L,
        M                    = SDL_SCANCODE_M,
        N                    = SDL_SCANCODE_N,
        O                    = SDL_SCANCODE_O,
        P                    = SDL_SCANCODE_P,
        Q                    = SDL_SCANCODE_Q,
        R                    = SDL_SCANCODE_R,
        S                    = SDL_SCANCODE_S,
        T                    = SDL_SCANCODE_T,
        U                    = SDL_SCANCODE_U,
        V                    = SDL_SCANCODE_V,
        W                    = SDL_SCANCODE_W,
        X                    = SDL_SCANCODE_X,
        Y                    = SDL_SCANCODE_Y,
        Z                    = SDL_SCANCODE_Z,
        ONE                  = SDL_SCANCODE_1,
        TWO                  = SDL_SCANCODE_2,
        THREE                = SDL_SCANCODE_3,
        FOUR                 = SDL_SCANCODE_4,
        FIVE                 = SDL_SCANCODE_5,
        SIX                  = SDL_SCANCODE_6,
        SEVEN                = SDL_SCANCODE_7,
        EIGHT                = SDL_SCANCODE_8,
        NINE                 = SDL_SCANCODE_9,
        ZERO                 = SDL_SCANCODE_0,
        RETURN               = SDL_SCANCODE_RETURN,
        ESCAPE               = SDL_SCANCODE_ESCAPE,
        BACKSPACE            = SDL_SCANCODE_BACKSPACE,
        TAB                  = SDL_SCANCODE_TAB,
        SPACE                = SDL_SCANCODE_SPACE,
        MINUS                = SDL_SCANCODE_MINUS,
        EQUALS               = SDL_SCANCODE_EQUALS,
        LEFTBRACKET          = SDL_SCANCODE_LEFTBRACKET,
        RIGHTBRACKET         = SDL_SCANCODE_RIGHTBRACKET,
        BACKSLASH            = SDL_SCANCODE_BACKSLASH,
        NONUSHASH            = SDL_SCANCODE_NONUSHASH,
        SEMICOLON            = SDL_SCANCODE_SEMICOLON,
        APOSTROPHE           = SDL_SCANCODE_APOSTROPHE,
        GRAVE                = SDL_SCANCODE_GRAVE,
        COMMA                = SDL_SCANCODE_COMMA,
        PERIOD               = SDL_SCANCODE_PERIOD,
        SLASH                = SDL_SCANCODE_SLASH,
        CAPSLOCK             = SDL_SCANCODE_CAPSLOCK,
        F1                   = SDL_SCANCODE_F1,
        F2                   = SDL_SCANCODE_F2,
        F3                   = SDL_SCANCODE_F3,
        F4                   = SDL_SCANCODE_F4,
        F5                   = SDL_SCANCODE_F5,
        F6                   = SDL_SCANCODE_F6,
        F7                   = SDL_SCANCODE_F7,
        F8                   = SDL_SCANCODE_F8,
        F9                   = SDL_SCANCODE_F9,
        F10                  = SDL_SCANCODE_F10,
        F11                  = SDL_SCANCODE_F11,
        F12                  = SDL_SCANCODE_F12,
        PRINTSCREEN          = SDL_SCANCODE_PRINTSCREEN,
        SCROLLLOCK           = SDL_SCANCODE_SCROLLLOCK,
        PAUSE                = SDL_SCANCODE_PAUSE,
        INSERT               = SDL_SCANCODE_INSERT,
        HOME                 = SDL_SCANCODE_HOME,
        PAGEUP               = SDL_SCANCODE_PAGEUP,
        DELETE               = SDL_SCANCODE_DELETE,
        END                  = SDL_SCANCODE_END,
        PAGEDOWN             = SDL_SCANCODE_PAGEDOWN,
        RIGHT                = SDL_SCANCODE_RIGHT,
        LEFT                 = SDL_SCANCODE_LEFT,
        DOWN                 = SDL_SCANCODE_DOWN,
        UP                   = SDL_SCANCODE_UP,
        NUMLOCKCLEAR         = SDL_SCANCODE_NUMLOCKCLEAR,
        KP_DIVIDE            = SDL_SCANCODE_KP_DIVIDE,
        KP_MULTIPLY          = SDL_SCANCODE_KP_MULTIPLY,
        KP_MINUS             = SDL_SCANCODE_KP_MINUS,
        KP_PLUS              = SDL_SCANCODE_KP_PLUS,
        KP_ENTER             = SDL_SCANCODE_KP_ENTER,
        KP_1                 = SDL_SCANCODE_KP_1,
        KP_2                 = SDL_SCANCODE_KP_2,
        KP_3                 = SDL_SCANCODE_KP_3,
        KP_4                 = SDL_SCANCODE_KP_4,
        KP_5                 = SDL_SCANCODE_KP_5,
        KP_6                 = SDL_SCANCODE_KP_6,
        KP_7                 = SDL_SCANCODE_KP_7,
        KP_8                 = SDL_SCANCODE_KP_8,
        KP_9                 = SDL_SCANCODE_KP_9,
        KP_0                 = SDL_SCANCODE_KP_0,
        KP_PERIOD            = SDL_SCANCODE_KP_PERIOD,
        NONUSBACKSLASH       = SDL_SCANCODE_NONUSBACKSLASH,
        APPLICATION          = SDL_SCANCODE_APPLICATION,
        POWER                = SDL_SCANCODE_POWER,
        KP_EQUALS            = SDL_SCANCODE_KP_EQUALS,
        F13                  = SDL_SCANCODE_F13,
        F14                  = SDL_SCANCODE_F14,
        F15                  = SDL_SCANCODE_F15,
        F16                  = SDL_SCANCODE_F16,
        F17                  = SDL_SCANCODE_F17,
        F18                  = SDL_SCANCODE_F18,
        F19                  = SDL_SCANCODE_F19,
        F20                  = SDL_SCANCODE_F20,
        F21                  = SDL_SCANCODE_F21,
        F22                  = SDL_SCANCODE_F22,
        F23                  = SDL_SCANCODE_F23,
        F24                  = SDL_SCANCODE_F24,
        EXECUTE              = SDL_SCANCODE_EXECUTE,
        HELP                 = SDL_SCANCODE_HELP,
        MENU                 = SDL_SCANCODE_MENU,
        SELECT               = SDL_SCANCODE_SELECT,
        STOP                 = SDL_SCANCODE_STOP,
        AGAIN                = SDL_SCANCODE_AGAIN,
        UNDO                 = SDL_SCANCODE_UNDO,
        CUT                  = SDL_SCANCODE_CUT,
        COPY                 = SDL_SCANCODE_COPY,
        PASTE                = SDL_SCANCODE_PASTE,
        FIND                 = SDL_SCANCODE_FIND,
        MUTE                 = SDL_SCANCODE_MUTE,
        VOLUMEUP             = SDL_SCANCODE_VOLUMEUP,
        VOLUMEDOWN           = SDL_SCANCODE_VOLUMEDOWN,
        KP_COMMA             = SDL_SCANCODE_KP_COMMA,
        KP_EQUALSAS400       = SDL_SCANCODE_KP_EQUALSAS400,
        INTERNATIONAL1       = SDL_SCANCODE_INTERNATIONAL1,
        INTERNATIONAL2       = SDL_SCANCODE_INTERNATIONAL2,
        INTERNATIONAL3       = SDL_SCANCODE_INTERNATIONAL3,
        INTERNATIONAL4       = SDL_SCANCODE_INTERNATIONAL4,
        INTERNATIONAL5       = SDL_SCANCODE_INTERNATIONAL5,
        INTERNATIONAL6       = SDL_SCANCODE_INTERNATIONAL6,
        INTERNATIONAL7       = SDL_SCANCODE_INTERNATIONAL7,
        INTERNATIONAL8       = SDL_SCANCODE_INTERNATIONAL8,
        INTERNATIONAL9       = SDL_SCANCODE_INTERNATIONAL9,
        LANG1                = SDL_SCANCODE_LANG1,
        LANG2                = SDL_SCANCODE_LANG2,
        LANG3                = SDL_SCANCODE_LANG3,
        LANG4                = SDL_SCANCODE_LANG4,
        LANG5                = SDL_SCANCODE_LANG5,
        LANG6                = SDL_SCANCODE_LANG6,
        LANG7                = SDL_SCANCODE_LANG7,
        LANG8                = SDL_SCANCODE_LANG8,
        LANG9                = SDL_SCANCODE_LANG9,
        ALTERASE             = SDL_SCANCODE_ALTERASE,
        SYSREQ               = SDL_SCANCODE_SYSREQ,
        CANCEL               = SDL_SCANCODE_CANCEL,
        CLEAR                = SDL_SCANCODE_CLEAR,
        PRIOR                = SDL_SCANCODE_PRIOR,
        RETURN2              = SDL_SCANCODE_RETURN2,
        SEPARATOR            = SDL_SCANCODE_SEPARATOR,
        OUT                  = SDL_SCANCODE_OUT,
        OPER                 = SDL_SCANCODE_OPER,
        CLEARAGAIN           = SDL_SCANCODE_CLEARAGAIN,
        CRSEL                = SDL_SCANCODE_CRSEL,
        EXSEL                = SDL_SCANCODE_EXSEL,
        KP_00                = SDL_SCANCODE_KP_00,
        KP_000               = SDL_SCANCODE_KP_000,
        THOUSANDSSEPARATOR   = SDL_SCANCODE_THOUSANDSSEPARATOR,
        DECIMALSEPARATOR     = SDL_SCANCODE_DECIMALSEPARATOR,
        CURRENCYUNIT         = SDL_SCANCODE_CURRENCYUNIT,
        CURRENCYSUBUNIT      = SDL_SCANCODE_CURRENCYSUBUNIT,
        KP_LEFTPAREN         = SDL_SCANCODE_KP_LEFTPAREN,
        KP_RIGHTPAREN        = SDL_SCANCODE_KP_RIGHTPAREN,
        KP_LEFTBRACE         = SDL_SCANCODE_KP_LEFTBRACE,
        KP_RIGHTBRACE        = SDL_SCANCODE_KP_RIGHTBRACE,
        KP_TAB               = SDL_SCANCODE_KP_TAB,
        KP_BACKSPACE         = SDL_SCANCODE_KP_BACKSPACE,
        KP_A                 = SDL_SCANCODE_KP_A,
        KP_B                 = SDL_SCANCODE_KP_B,
        KP_C                 = SDL_SCANCODE_KP_C,
        KP_D                 = SDL_SCANCODE_KP_D,
        KP_E                 = SDL_SCANCODE_KP_E,
        KP_F                 = SDL_SCANCODE_KP_F,
        KP_XOR               = SDL_SCANCODE_KP_XOR,
        KP_POWER             = SDL_SCANCODE_KP_POWER,
        KP_PERCENT           = SDL_SCANCODE_KP_PERCENT,
        KP_LESS              = SDL_SCANCODE_KP_LESS,
        KP_GREATER           = SDL_SCANCODE_KP_GREATER,
        KP_AMPERSAND         = SDL_SCANCODE_KP_AMPERSAND,
        KP_DBLAMPERSAND      = SDL_SCANCODE_KP_DBLAMPERSAND,
        KP_VERTICALBAR       = SDL_SCANCODE_KP_VERTICALBAR,
        KP_DBLVERTICALBAR    = SDL_SCANCODE_KP_DBLVERTICALBAR,
        KP_COLON             = SDL_SCANCODE_KP_COLON,
        KP_HASH              = SDL_SCANCODE_KP_HASH,
        KP_SPACE             = SDL_SCANCODE_KP_SPACE,
        KP_AT                = SDL_SCANCODE_KP_AT,
        KP_EXCLAM            = SDL_SCANCODE_KP_EXCLAM,
        KP_MEMSTORE          = SDL_SCANCODE_KP_MEMSTORE,
        KP_MEMRECALL         = SDL_SCANCODE_KP_MEMRECALL,
        KP_MEMCLEAR          = SDL_SCANCODE_KP_MEMCLEAR,
        KP_MEMADD            = SDL_SCANCODE_KP_MEMADD,
        KP_MEMSUBTRACT       = SDL_SCANCODE_KP_MEMSUBTRACT,
        KP_MEMMULTIPLY       = SDL_SCANCODE_KP_MEMMULTIPLY,
        KP_MEMDIVIDE         = SDL_SCANCODE_KP_MEMDIVIDE,
        KP_PLUSMINUS         = SDL_SCANCODE_KP_PLUSMINUS,
        KP_CLEAR             = SDL_SCANCODE_KP_CLEAR,
        KP_CLEARENTRY        = SDL_SCANCODE_KP_CLEARENTRY,
        KP_BINARY            = SDL_SCANCODE_KP_BINARY,
        KP_OCTAL             = SDL_SCANCODE_KP_OCTAL,
        KP_DECIMAL           = SDL_SCANCODE_KP_DECIMAL,
        KP_HEXADECIMAL       = SDL_SCANCODE_KP_HEXADECIMAL,
        LCTRL                = SDL_SCANCODE_LCTRL,
        LSHIFT               = SDL_SCANCODE_LSHIFT,
        LALT                 = SDL_SCANCODE_LALT,
        LGUI                 = SDL_SCANCODE_LGUI,
        RCTRL                = SDL_SCANCODE_RCTRL,
        RSHIFT               = SDL_SCANCODE_RSHIFT,
        RALT                 = SDL_SCANCODE_RALT,
        RGUI                 = SDL_SCANCODE_RGUI,
        MODE                 = SDL_SCANCODE_MODE,
        SLEEP                = SDL_SCANCODE_SLEEP,
        WAKE                 = SDL_SCANCODE_WAKE,
        CHANNEL_INCREMENT    = SDL_SCANCODE_CHANNEL_INCREMENT,
        CHANNEL_DECREMENT    = SDL_SCANCODE_CHANNEL_DECREMENT,
        MEDIA_PLAY           = SDL_SCANCODE_MEDIA_PLAY,
        MEDIA_PAUSE          = SDL_SCANCODE_MEDIA_PAUSE,
        MEDIA_RECORD         = SDL_SCANCODE_MEDIA_RECORD,
        MEDIA_FAST_FORWARD   = SDL_SCANCODE_MEDIA_FAST_FORWARD,
        MEDIA_REWIND         = SDL_SCANCODE_MEDIA_REWIND,
        MEDIA_NEXT_TRACK     = SDL_SCANCODE_MEDIA_NEXT_TRACK,
        MEDIA_PREVIOUS_TRACK = SDL_SCANCODE_MEDIA_PREVIOUS_TRACK,
        MEDIA_STOP           = SDL_SCANCODE_MEDIA_STOP,
        MEDIA_EJECT          = SDL_SCANCODE_MEDIA_EJECT,
        MEDIA_PLAY_PAUSE     = SDL_SCANCODE_MEDIA_PLAY_PAUSE,
        MEDIA_SELECT         = SDL_SCANCODE_MEDIA_SELECT,
        AC_NEW               = SDL_SCANCODE_AC_NEW,
        AC_OPEN              = SDL_SCANCODE_AC_OPEN,
        AC_CLOSE             = SDL_SCANCODE_AC_CLOSE,
        AC_EXIT              = SDL_SCANCODE_AC_EXIT,
        AC_SAVE              = SDL_SCANCODE_AC_SAVE,
        AC_PRINT             = SDL_SCANCODE_AC_PRINT,
        AC_PROPERTIES        = SDL_SCANCODE_AC_PROPERTIES,
        AC_SEARCH            = SDL_SCANCODE_AC_SEARCH,
        AC_HOME              = SDL_SCANCODE_AC_HOME,
        AC_BACK              = SDL_SCANCODE_AC_BACK,
        AC_FORWARD           = SDL_SCANCODE_AC_FORWARD,
        AC_STOP              = SDL_SCANCODE_AC_STOP,
        AC_REFRESH           = SDL_SCANCODE_AC_REFRESH,
        AC_BOOKMARKS         = SDL_SCANCODE_AC_BOOKMARKS,
        SOFTLEFT             = SDL_SCANCODE_SOFTLEFT,
        SOFTRIGHT            = SDL_SCANCODE_SOFTRIGHT,
        CALL                 = SDL_SCANCODE_CALL,
        ENDCALL              = SDL_SCANCODE_ENDCALL
    };

    struct MouseMoveEvent
    {
        glm::vec2 position;
        glm::vec2 releative;
    };

    struct MouseButtonDownEvent
    {
        glm::vec2 position;
        MouseButton button;
    };

    struct MouseButtonUpEvent
    {
        glm::vec2 position;
        MouseButton button;
    };

    struct MouseWheelEvent
    {
        glm::vec2 releative;
    };

    struct KeyDownEvent
    {
        KeyMod   mod;
        KeyCode  key;
        ScanCode scan;
    };

    struct KeyUpEvent
    {
        KeyMod   mod;
        KeyCode  key;
        ScanCode scan;
    };

    using InputEvent = std::variant<MouseMoveEvent, MouseButtonDownEvent, MouseButtonUpEvent, MouseWheelEvent,
                                    KeyDownEvent, KeyUpEvent>;

    //! Install an observer for the quit event.
    //!
    //! The quit event is issued when either the last window is closed or
    //! the operating system requests the application to terminate.
    PKZO_EXPORT rsig::connection on_quit(const std::function<void ()>& handler);

    //! Install a generic observer for all input events.
    //!
    //! The input event is issues when any mouse or keyboard input is triggered.
    //! For a more fine grained control, use Mouse or Keyboard directly.
    //!
    //! @see Mouse
    //! @see Keyboard
    PKZO_EXPORT rsig::connection on_input(const std::function<void (const InputEvent& event)>& handler);

    //! Distribute all pending OS events to the different consumers.
    PKZO_EXPORT void route_events();
}
