name: Auto approve

on:
  issue_comment:
    types:
      - created

env:
  APPROVAL_USER: 'rioki'
  APPROVAL_KEYWORD: 'LGTM'
  APPROVAL_BODY: 'Let`s get this merged then.'

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/github-script@v6
      name: Approve LGTM Review
      if: github.actor == ${{ env.APPROVAL_USER }} &&  contains(github.event.comment.body, ${{ env.APPROVAL_KEYWORD }})
      with:
        script: |
          github.rest.pulls.createReview({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            review_id: 1,
            event: 'APPROVE',
            body: $APPROVAL_BODY
          })
