name: Automated Code Review

on:
  pull_request:
    types: [opened, synchronize]
    
permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    name: GPT-4 Code Review
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Optional
          LANGUAGE: English
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          MODEL: gpt-4 
          PROMPT: "Please review the code from the following code diff:"
          top_p: 1 
          temperature: 1 
          max_tokens: 5000
          MAX_PATCH_LENGTH: 10000 
