name: MSBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  packages: write

env:
  VCPKG_COMMIT: d567b667adba0e72c5c3931ddbe745b66aa34b73

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [x86, x64]
        include:
          - platform: x86
            triplet: x86-windows
          - platform: x64
            triplet: x64-windows
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Restore from cache and install vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: ${{ env.VCPKG_COMMIT }}
    - name: Integrate vcpkg in MSBuild
      shell: 'bash'
      run: >
        ./vcpkg/vcpkg integrate install
    - name: Build (Debug)
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Debug /property:Platform=${{matrix.platform}} pkzo.sln
    - name: Test (Debug)
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: bin/${{matrix.platform}}/Debug/pkzo-test.exe --gtest_filter=-*.GRAPH_*:*.NOCI_*
    - name: Build (Release)
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Release /property:Platform=${{matrix.platform}} pkzo.sln
    - name: Test (Release)
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: bin/${{matrix.platform}}/Release/pkzo-test.exe --gtest_filter=-*.GRAPH_*:*.NOCI_*
