name: MSBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Restore from cache and install vcpkg
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: e99d9a4facea9d7e15a91212364d7a12762b7512
    - name: Integrate vcpkg 
      working-directory: ${{steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT}}
      run: vcpkg.exe integrate install
    - name: Build Debug x86
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Debug /property:Platform=x86 ice.sln
    - name: Build Debug x64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Debug /property:Platform=x64 ice.sln
    - name: Build Release x86
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Release /property:Platform=x86 ice.sln
    - name: Build Release x64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Release /property:Platform=x64 ice.sln
    - name: Test Release x86
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: bin/x64/Release/ice-test.exe --gtest_filter=-*.GRAPHICAL_*
    - name: Test Release x64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: bin/x64/Release/ice-test.exe --gtest_filter=-*.GRAPHICAL_*
